name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
       #新建一个名为checkout_actions的步骤
      - name: checkout_actions
        #使用checkout@v2这个action获取源码
        uses: actions/checkout@v2 
      - name: dependcy
        uses: actions/python@v1
        with:
            python-version: 3.7
            run: bash ./signIn.python
        
